name: Rust

on:
  push:
    branches: 
      - "**"
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: cargo check --all-targets
    - name: check style
      run: cargo fmt --all -- --check
    - name: Lint
      run: cargo clippy --all-targets -- -W clippy::pedantic
    - name: Run tests
      run: cargo test
